# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64af61467c939ca2350e3bc4929f5acc8dc41269cdfdc19b7f7b1a739af58cb63352f87c9bd8816b9adf6e519699fa42b819b0833bb0d5d8f9ee7a6291dfdb44

test:
  secret_key_base: 2dfaf152daee810a6c0bc88b45f076775a3bba0bb8539d79e2b3b1fa3fdd929c3eab0d4a211afb3899f452fa4c0f3b469e7cff7ba76ba5dba764a69933f4e39a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
